[package]
name = "simple-tcp-server-rs"
version = "0.1.0"
authors = ["Cheng <cheng404@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
